# Kriti CircuitX

In [23]:
def input_locations(matrix2x2):
    input_matrix = matrix2x2[:,:2]
    types_matrix = (input_matrix/10).astype(int)
    return (types_matrix == 8) | (types_matrix == 9) | (types_matrix == 10)

In [24]:
import numpy as np
matrix2 = np.array([[91,81,11],[11,0,111]])#,[92,101,12],[41,51,13],[102,82,21],[21,12,41],[12,11,51],[13,0,111]])

In [25]:
matrix2

array([[ 91,  81,  11],
       [ 11,   0, 111]])

In [26]:
input_locations(matrix) 

array([[ True,  True],
       [ True,  True],
       [False, False],
       [ True,  True],
       [False, False],
       [False, False],
       [False, False]])

In [5]:
def unique_init_inputs(matrix2x2):
    input_loc = input_locations(matrix2x2)
    total_unique_inputs = np.any((matrix2x2/10).astype(int) == 8).astype(int) + np.any((matrix2x2/10).astype(int) == 9).astype(int) + np.any((matrix2x2/10).astype(int) == 10).astype(int)
    mask_red = (matrix2x2/10).astype(int) == 8
    mask_green = (matrix2x2/10).astype(int) == 9
    mask_blue = (matrix2x2/10).astype(int) == 10
    return total_unique_inputs,[mask_red,mask_green,mask_blue]

##### *input_counter* is working correctly

In [6]:
def all_possible_inp_maker(matrix2x2):
    total_inps,_ = unique_init_inputs(matrix2x2)  #This was to find the no. of all the inputs which was WRONG
    arr = np.zeros(total_inps)
    all_bin_list = []
    for i in range(np.power(2,total_inps)):
        bin_string = bin(i)[2:].rjust(total_inps,'0')
        all_bin_list.append([i for i in bin_string])
    return np.array(all_bin_list).astype(int)

In [22]:
all_possible_inp_maker(matrix)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [8]:
def input_value_putter(matrix2x2,vector_to_put):
    unique_inputs, masks = unique_init_inputs(matrix2x2)
    new_matrix = np.zeros_like(matrix2x2)
    for i in range(unique_inputs):
        new_matrix[masks[i]] = vector_to_put[i]
    return new_matrix    

# Create a while  loop, over the matrix made by removing input rows after their outputs are put in the right places

In [9]:
def output_generator_4_inputs(matrix2x2, binary_vector):
    
    #Where's binary_vector????           Tick
    
#Initial Evaluation directly from inputs    
    
    matrix_4_op = input_value_putter(matrix2x2,binary_vector)
    out_mat = matrix_4_op
    input_loc = input_locations(matrix2x2)
    cache = np.zeros_like(input_loc).astype(bool)
#INITIALIZE THE INPUT FOR THE NOT GATES    
    for i,val in np.ndenumerate(matrix2x2[:,2]):
            if int(val/10) == 7:
                if input_loc[i,0] == True:
                    input_loc[i,1] = True        
        

    
    for i in range(matrix_4_op.shape[0]):
        if input_loc[i,0]:
    
            if int(matrix2x2[i,2]/10) == 1:
                out_mat[i,2] = out_mat[i,0] and out_mat[i,1]
            elif int(matrix2x2[i,2]/10) == 2:
                out_mat[i,2] = out_mat[i,0] or out_mat[i,1]
            elif int(matrix2x2[i,2]/10) == 3:
                out_mat[i,2] = not(out_mat[i,0] and out_mat[i,1])
            elif int(matrix2x2[i,2]/10) == 4:
                out_mat[i,2] = not(out_mat[i,0] or out_mat[i,1])
            elif int(matrix2x2[i,2]/10) == 5:
                out_mat[i,2] = out_mat[i,0] ^ out_mat[i,1]
            elif int(matrix2x2[i,2]/10) == 6:
                out_mat[i,2] = not(out_mat[i,0] ^ out_mat[i,1])
            elif int(matrix2x2[i,2]/10) == 7:
                out_mat[i,2] = not(out_mat[i,0])
            
        #checking 111, i.e output
        
            #elif int(matrix_4_op[i,2]) == 111:
             #   output = matrix_4_op[i,2]
                
    count = 0
    #print(input_loc,out_mat)
    while True:
        count+=1
#PUT OUTPUT TO NEXT INPUTS
        #inserting the values just calculated, in out_mat to the specefic locations in the two input columns::-- 
        for i,outs in np.ndenumerate(matrix2x2[:,2]):
            if input_loc[i,0] & input_loc[i,1]:
                out_mat[:,:2][matrix2x2[:,:2] == outs] = out_mat[:,2][matrix2x2[:,2] == outs]
 
        #Check the fucking pairs and initialize the input_loc again
#SIMILARILY, UPDATE THE input_loc BOOL TABLE                                                            
        pairs_loc = input_loc[:,0] & input_loc[:,1]
#Long Term Memory    
        input_loc = np.zeros_like(input_loc).astype(bool) 
        for i in range(cache.shape[0]):
            if (((cache[i,0] ==True) & (cache[i,1]==False))) :#| ((cache[i,0] ==True) & (cache[i,1]==False))):
                input_loc[i,0] = True
            elif (((cache[i,0] ==False) & (cache[i,1]==True))):
                input_loc[i,1] = True
         
        for i,val in np.ndenumerate(pairs_loc):
            if val:
                input_loc[matrix2x2[:,:2] == matrix2x2[i,2]] = True
                
                
#Checks whether the next input is for NOT gate, AND IF IT IS, PUT A TRUE ON IT'S NEXT ROW TOO (I know it's an inefficient implementation!!)    
        for i,val in np.ndenumerate(matrix2x2[:,2]):
            if int(val/10) == 7:
                if input_loc[i,0] == True:
                    input_loc[i,1] = True        

            
#LOOP BREAKING CONDITION            
        #Below Condition is for the breaking from the loop when the corresponding row in which the flow is have output as '111'    
            
        if np.any(matrix2x2[input_loc[:,0] == True][:,2] == 111):
            output = out_mat[:,0][matrix2x2[:,2] == 111]
            break
        
#CALCULATE NEXT OUTPUTS        
        #Now, the new pairs are made (if there's any) and now we need to calculate the new outputs to put in out_mat
        
        for i in range(matrix_4_op.shape[0]):
            if input_loc[i,0] & input_loc[i,1]:

                if int(matrix2x2[i,2]/10) == 1:
                    out_mat[i,2] = out_mat[i,0] and out_mat[i,1]
                elif int(matrix2x2[i,2]/10) == 2:
                    out_mat[i,2] = out_mat[i,0] or out_mat[i,1]
                elif int(matrix2x2[i,2]/10) == 3:
                    out_mat[i,2] = not(out_mat[i,0] and out_mat[i,1])
                elif int(matrix2x2[i,2]/10) == 4:
                    out_mat[i,2] = not(out_mat[i,0] or out_mat[i,1])
                elif int(matrix2x2[i,2]/10) == 5:
                    out_mat[i,2] = out_mat[i,0] ^ out_mat[i,1]
                elif int(matrix2x2[i,2]/10) == 6:
                    out_mat[i,2] = not(out_mat[i,0] ^ out_mat[i,1])
                elif int(matrix2x2[i,2]/10) == 7:
                    out_mat[i,2] = not(out_mat[i,0])
        
        #verb_count+=1
        #print('While Loop number {}'.format(verb_count))
    
        #print(input_loc,out_mat)
        if count==1:
            cache = input_loc
    return output,out_mat,input_loc
    
    #After this the input_pair_matrix[:,:2] will be filled by 1's where the pairs are there.    
        

In [10]:
matrix

array([[ 91,  81,  11],
       [ 92, 101,  12],
       [ 41,  51,  13],
       [102,  82,  21],
       [ 21,  12,  41],
       [ 12,  11,  51],
       [ 13,   0, 111]])

In [11]:
def truth_table_generator(matrix2x2):
    binary_vectorS = all_possible_inp_maker(matrix2x2)
    TT = []
    for i in range(binary_vectorS.shape[0]):
        output, _ , _ = output_generator_4_inputs(matrix2x2,binary_vectorS[i])
        TT.append([binary_vectorS[i],output])
    print("Outputs:")
    print("Red | Green | Blue ::: OUTPUT")
    return np.array(TT)

In [14]:
(truth_table_generator(matrix1))

Outputs:
Red | Green | Blue ::: OUTPUT


array([[array([0, 0]), array([1])],
       [array([0, 1]), array([0])],
       [array([1, 0]), array([0])],
       [array([1, 1]), array([0])]], dtype=object)

In [12]:
matrix1 = np.array([[81,91,21],
                    [82,0,71],
                    [71,21,61],
                    [61,0,72],
                    [72,71,11],
                    [11,0,111]]
                    )

In [17]:
matrix1

array([[ 81,  91,  21],
       [ 82,   0,  71],
       [ 71,  21,  61],
       [ 61,   0,  72],
       [ 72,  71,  11],
       [ 11,   0, 111]])

In [15]:
input_locations(matrix1),

(array([[ True,  True],
        [ True, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False]]),)

In [16]:
input_loc = input_locations(matrix1)

In [27]:
import KritiCXLogicDeducer

In [29]:
KritiCXLogicDeducer.truth_table_generator(matrix2)

Outputs:
['Red', 'Green']


array([[array([0, 0]), array([0])],
       [array([0, 1]), array([0])],
       [array([1, 0]), array([0])],
       [array([1, 1]), array([1])]], dtype=object)

In [31]:
struct = np.array([[91,81,41],[0,0,111]])

In [34]:
struct[-1,:]
num_rows = struct.shape[0]

In [40]:
sec_last_elem  =  struct[num_rows-2,2]

In [41]:
sec_last_elem

41

In [42]:
struct[-1,0] = struct[struct.shape[0]-2,2]

In [43]:
struct

array([[ 91,  81,  41],
       [ 41,   0, 111]])